"""
typical_data_ranges.py
───────────────────────────────────────────────────────
AUTO-GENERATED by parse_typical_data.py on 2026-06-17 16:21:00
DO NOT EDIT MANUALLY.

To update values:
  1. Edit inout/Typical_Data.f90
  2. Run: python parse_typical_data.py
"""

PROPELLANTS = [
    "Liquid Hidrogen / Liquid Oxigen",  # index 1
    "Liquid Kerosene / Liquid Oxigen",  # index 2
    "Liquid Methane  / Liquid Oxigne",  # index 3
    "UDMH/LOX",  # index 4
    "UDMH/AK-271",  # index 5
    "UDMH/N2O4",  # index 6
    "Aerozine50/N2O4",  # index 7
    "MH/Nitric Acid",  # index 8
]

CYCLES = [
    "Aproximates Engine Perfermoance Only Base On Propellant/Oxidizer",  # index 0
    "Staged Combustion",  # index 1
    "Gas Generator",  # index 2
    "Expander",  # index 3
    "Electric Pump",  # index 4
    "Pressure",  # index 5
]

# Key: (propellant_index, cycle_index)
# Value: (isp_lower, isp_upper, isp_mean, ks_lower, ks_upper, ks_mean)
# Value is None for explicitly invalid combinations.
TYPICAL_DATA = {
    # Liquid Hidrogen / Liquid Oxigen
    (1, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (1, 1): (445.6, 454.5, 451.5,  0.0666, 0.0968, 0.079),
    (1, 2): (405.0, 428.1, 414.367,  0.0666, 0.0968, 0.079),
    (1, 3): (425.0, 425.0, 425.0,  0.0666, 0.0968, 0.079),
    (1, 4): None,  # invalid combination
    (1, 5): None,  # invalid combination

    # Liquid Kerosene / Liquid Oxigen
    (2, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (2, 1): (337.2, 338.4, 337.625,  0.0666, 0.0968, 0.079),
    (2, 2): (283.9, 320.2, 302.625,  0.0666, 0.0968, 0.079),
    (2, 3): None,  # invalid combination
    (2, 4): None,  # invalid combination
    (2, 5): None,  # invalid combination

    # Liquid Methane  / Liquid Oxigne
    (3, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (3, 1): (350.0, 365.0, 357.5,  0.0666, 0.0968, 0.079),
    (3, 2): None,  # invalid combination
    (3, 3): None,  # invalid combination
    (3, 4): None,  # invalid combination
    (3, 5): None,  # invalid combination

    # UDMH/LOX
    (4, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (4, 1): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (4, 2): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (4, 3): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (4, 4): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (4, 5): None,  # invalid combination

    # UDMH/AK-271
    (5, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (5, 1): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (5, 2): (289.0, 289.0, 289.0,  0.0666, 0.0968, 0.079),
    (5, 3): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (5, 4): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (5, 5): None,  # invalid combination

    # UDMH/N2O4
    (6, 0): (315.8, 315.8, 315.8,  0.0666, 0.0968, 0.079),
    (6, 1): (315.8, 315.8, 315.8,  0.0666, 0.0968, 0.079),
    (6, 2): None,  # invalid combination
    (6, 3): None,  # invalid combination
    (6, 4): None,  # invalid combination
    (6, 5): None,  # invalid combination

    # Aerozine50/N2O4
    (7, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (7, 1): None,  # invalid combination
    (7, 2): (296.0, 303.9, 299.95,  0.0666, 0.0968, 0.079),
    (7, 3): None,  # invalid combination
    (7, 4): None,  # invalid combination
    (7, 5): None,  # invalid combination

    # MH/Nitric Acid
    (8, 0): None,  # invalid combination
    (8, 1): None,  # invalid combination
    (8, 2): None,  # invalid combination
    (8, 3): None,  # invalid combination
    (8, 4): None,  # invalid combination
    (8, 5): None,  # invalid combination

}
