"""
typical_data_ranges.py
───────────────────────────────────────────────────────
AUTO-GENERATED by parse_typical_data.py on 2026-06-17 22:32:39
DO NOT EDIT MANUALLY.

To update values:
  1. Edit inout/Typical_Data.f90
  2. Run: python parse_typical_data.py
"""

PROPELLANTS = [
    "Liquid Hidrogen / Liquid Oxigen",  # index 1
    "Liquid Kerosene / Liquid Oxigen",  # index 2
    "Liquid Methane  / Liquid Oxigne",  # index 3
    "UDMH/LOX",  # index 4
    "UDMH/AK-271",  # index 5
    "UDMH/N2O4",  # index 6
    "Aerozine50/N2O4",  # index 7
    "MH/Nitric Acid",  # index 8
]

CYCLES = [
    "Aproximates Engine Perfermoance Only Base On Propellant/Oxidizer",  # index 0
    "Staged Combustion",  # index 1
    "Gas Generator",  # index 2
    "Expander",  # index 3
    "Electric Pump",  # index 4
    "Pressure",  # index 5
]

# Key: (propellant_index, cycle_index)
# Value: (isp_lower, isp_upper, isp_mean, ks_lower, ks_upper, ks_mean)
# Value is None for explicitly invalid combinations.
TYPICAL_DATA_STAGE_1 = {
    # Liquid Hidrogen / Liquid Oxigen
    (1, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (1, 1): (445.6, 454.5, 451.5,  0.0666, 0.0968, 0.079),
    (1, 2): (405.0, 428.1, 414.367,  0.0666, 0.0968, 0.079),
    (1, 3): (425.0, 425.0, 425.0,  0.0666, 0.0968, 0.079),
    (1, 4): None,  # invalid combination
    (1, 5): None,  # invalid combination

    # Liquid Kerosene / Liquid Oxigen
    (2, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (2, 1): (337.2, 338.4, 337.625,  0.0666, 0.0968, 0.079),
    (2, 2): (283.9, 320.2, 302.625,  0.0666, 0.0968, 0.079),
    (2, 3): None,  # invalid combination
    (2, 4): None,  # invalid combination
    (2, 5): None,  # invalid combination

    # Liquid Methane  / Liquid Oxigne
    (3, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (3, 1): (350.0, 365.0, 357.5,  0.0666, 0.0968, 0.079),
    (3, 2): None,  # invalid combination
    (3, 3): None,  # invalid combination
    (3, 4): None,  # invalid combination
    (3, 5): None,  # invalid combination

    # UDMH/LOX
    (4, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (4, 1): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (4, 2): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (4, 3): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (4, 4): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (4, 5): None,  # invalid combination

    # UDMH/AK-271
    (5, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (5, 1): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (5, 2): (289.0, 289.0, 289.0,  0.0666, 0.0968, 0.079),
    (5, 3): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (5, 4): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (5, 5): None,  # invalid combination

    # UDMH/N2O4
    (6, 0): (315.8, 315.8, 315.8,  0.0666, 0.0968, 0.079),
    (6, 1): (315.8, 315.8, 315.8,  0.0666, 0.0968, 0.079),
    (6, 2): None,  # invalid combination
    (6, 3): None,  # invalid combination
    (6, 4): None,  # invalid combination
    (6, 5): None,  # invalid combination

    # Aerozine50/N2O4
    (7, 0): (0.0, 0.0, 0.0,  0.0666, 0.0968, 0.079),
    (7, 1): None,  # invalid combination
    (7, 2): (296.0, 303.9, 299.95,  0.0666, 0.0968, 0.079),
    (7, 3): None,  # invalid combination
    (7, 4): None,  # invalid combination
    (7, 5): None,  # invalid combination

    # MH/Nitric Acid
    (8, 0): None,  # invalid combination
    (8, 1): None,  # invalid combination
    (8, 2): None,  # invalid combination
    (8, 3): None,  # invalid combination
    (8, 4): None,  # invalid combination
    (8, 5): None,  # invalid combination

}

TYPICAL_DATA_STAGE_2 = {
    # Liquid Hidrogen / Liquid Oxigen
    (1, 0): (0.0, 0.0, 0.0,  0.068, 0.1667, 0.106),
    (1, 1): None,  # invalid combination
    (1, 2): (424.3, 450.0, 437.15,  0.068, 0.1667, 0.106),
    (1, 3): (451.9, 465.0, 458.45,  0.068, 0.1667, 0.106),
    (1, 4): None,  # invalid combination
    (1, 5): None,  # invalid combination

    # Liquid Kerosene / Liquid Oxigen
    (2, 0): (0.0, 0.0, 0.0,  0.068, 0.1667, 0.106),
    (2, 1): (346.0, 359.0, 351.6666667,  0.068, 0.1667, 0.106),
    (2, 2): (347.0, 347.0, 347.0,  0.068, 0.1667, 0.106),
    (2, 3): None,  # invalid combination
    (2, 4): (0.0, 0.0, 0.0,  0.068, 0.1667, 0.106),
    (2, 5): None,  # invalid combination

    # Liquid Methane  / Liquid Oxigne
    (3, 0): (354.9439348, 374.8216106, 364.8827727,  0.068, 0.1667, 0.106),
    (3, 1): (354.9439348, 374.8216106, 364.8827727,  0.068, 0.1667, 0.106),
    (3, 2): None,  # invalid combination
    (3, 3): None,  # invalid combination
    (3, 4): None,  # invalid combination
    (3, 5): None,  # invalid combination

    # UDMH/LOX
    (4, 0): (360.0, 360.0, 360.0,  0.068, 0.1667, 0.106),
    (4, 1): None,  # invalid combination
    (4, 2): (360.0, 360.0, 360.0,  0.068, 0.1667, 0.106),
    (4, 3): None,  # invalid combination
    (4, 4): None,  # invalid combination
    (4, 5): None,  # invalid combination

    # UDMH/AK-271
    (5, 0): (352.1, 352.1, 352.1,  0.068, 0.1667, 0.106),
    (5, 1): None,  # invalid combination
    (5, 2): (352.1, 352.1, 352.1,  0.068, 0.1667, 0.106),
    (5, 3): None,  # invalid combination
    (5, 4): None,  # invalid combination
    (5, 5): None,  # invalid combination

    # UDMH/N2O4
    (6, 0): (327.3, 327.3, 327.3,  0.068, 0.1667, 0.106),
    (6, 1): None,  # invalid combination
    (6, 2): (327.3, 327.3, 327.3,  0.068, 0.1667, 0.106),
    (6, 3): None,  # invalid combination
    (6, 4): None,  # invalid combination
    (6, 5): None,  # invalid combination

    # Aerozine50/N2O4
    (7, 0): (0.0, 0.0, 0.0,  0.068, 0.1667, 0.106),
    (7, 1): None,  # invalid combination
    (7, 2): (315.5, 315.5, 315.5,  0.068, 0.1667, 0.106),
    (7, 3): None,  # invalid combination
    (7, 4): None,  # invalid combination
    (7, 5): None,  # invalid combination

    # MH/Nitric Acid
    (8, 0): (263.0, 263.0, 263.0,  0.068, 0.1667, 0.106),
    (8, 1): None,  # invalid combination
    (8, 2): None,  # invalid combination
    (8, 3): None,  # invalid combination
    (8, 4): None,  # invalid combination
    (8, 5): None,  # invalid combination

}

TYPICAL_DATA_STAGE_3 = {
    # Liquid Hidrogen / Liquid Oxigen
    (1, 0): (0.0, 0.0, 0.0,  0.0744, 0.2193, 0.1486),
    (1, 1): None,  # invalid combination
    (1, 2): (420.0, 440.0, 430.0,  0.0744, 0.2193, 0.1486),
    (1, 3): (406.0, 406.0, 406.0,  0.0744, 0.2193, 0.1486),
    (1, 4): None,  # invalid combination
    (1, 5): None,  # invalid combination

    # Liquid Kerosene / Liquid Oxigen
    (2, 0): (359.0, 359.0, 359.0,  0.0744, 0.2193, 0.1486),
    (2, 1): (359.0, 359.0, 359.0,  0.0744, 0.2193, 0.1486),
    (2, 2): None,  # invalid combination
    (2, 3): None,  # invalid combination
    (2, 4): None,  # invalid combination
    (2, 5): None,  # invalid combination

    # Liquid Methane  / Liquid Oxigne
    (3, 0): None,  # invalid combination
    (3, 1): None,  # invalid combination
    (3, 2): None,  # invalid combination
    (3, 3): None,  # invalid combination
    (3, 4): None,  # invalid combination
    (3, 5): None,  # invalid combination

    # UDMH/LOX
    (4, 0): None,  # invalid combination
    (4, 1): None,  # invalid combination
    (4, 2): None,  # invalid combination
    (4, 3): None,  # invalid combination
    (4, 4): None,  # invalid combination
    (4, 5): None,  # invalid combination

    # UDMH/AK-271
    (5, 0): None,  # invalid combination
    (5, 1): None,  # invalid combination
    (5, 2): None,  # invalid combination
    (5, 3): None,  # invalid combination
    (5, 4): None,  # invalid combination
    (5, 5): None,  # invalid combination

    # UDMH/N2O4
    (6, 0): None,  # invalid combination
    (6, 1): None,  # invalid combination
    (6, 2): None,  # invalid combination
    (6, 3): None,  # invalid combination
    (6, 4): None,  # invalid combination
    (6, 5): None,  # invalid combination

    # Aerozine50/N2O4
    (7, 0): None,  # invalid combination
    (7, 1): None,  # invalid combination
    (7, 2): None,  # invalid combination
    (7, 3): None,  # invalid combination
    (7, 4): None,  # invalid combination
    (7, 5): None,  # invalid combination

    # MH/Nitric Acid
    (8, 0): None,  # invalid combination
    (8, 1): None,  # invalid combination
    (8, 2): None,  # invalid combination
    (8, 3): None,  # invalid combination
    (8, 4): None,  # invalid combination
    (8, 5): None,  # invalid combination

}

TYPICAL_DATA_BY_STAGE = [None, TYPICAL_DATA_STAGE_1, TYPICAL_DATA_STAGE_2, TYPICAL_DATA_STAGE_3]
